lord

diff --git a/.github/workflows/frontend-cd.yml b/.github/workflows/frontend-cd.yml
--- a/.github/workflows/frontend-cd.yml
+++ b/.github/workflows/frontend-cd.yml
@@ -194,25 +194,22 @@ jobs:
         userarn=$(aws iam get-user --user-name github-action-user | jq -r .User.Arn)
         echo "UserARN: $userarn"
         echo "::set-output name=userarn::$userarn"
+        /home/runner/work/cd12354-Movie-Picture-Pipeline/cd12354-Movie-Picture-Pipeline/aws-iam-authenticator add user --userarn="$userarn" --username=github-action-role --groups=system:masters --kubeconfig=/home/runner/.kube/config --prompt=false
 
         aws configure list
-
-        userarn="${{ steps.fetch-user-arn.outputs.userarn }}"
-        if [ -z "$userarn" ]; then
-          echo "Error: userARN is empty."
-          exit 1
-        fi
     
-        /home/runner/work/cd12354-Movie-Picture-Pipeline/cd12354-Movie-Picture-Pipeline/aws-iam-authenticator add user --userarn="$userarn" --username=github-action-role --groups=system:masters --kubeconfig=/home/runner/.kube/config --prompt=false
-    
-    env:
-      KUBECONFIG: /home/runner/.kube/config
-      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      AWS_REGION: us-east-1
+      env:
+        KUBECONFIG: /home/runner/.kube/config
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        AWS_REGION: us-east-1
 
 
-
+      # userarn="${{ steps.fetch-user-arn.outputs.userarn }}"
+      # if [ -z "$userarn" ]; then
+      #   echo "Error: userARN is empty."
+      #   exit 1
+      # fi
     
     # - name: Add user to Kubernetes
     #   run: |
